# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='\u7559\u8a00')),
                ('status', models.BooleanField(default=False, verbose_name='\u72b6\u6001')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65e5\u671f')),
            ],
        ),
    ]
