# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myglobal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixstatus',
            options={'verbose_name': '\u7ef4\u4fee\u72b6\u6001', 'verbose_name_plural': '\u7ef4\u4fee\u72b6\u6001'},
        ),
    ]
