# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('active', models.BooleanField(verbose_name='\u53d1\u8868\u72b6\u6001')),
                ('publish_time', models.DateTimeField(verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
    ]
