# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u7535\u8bdd'),
        ),
    ]
