# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_auto_20170113_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avator',
            field=models.ImageField(default=None, null=True, upload_to='user/avators/', verbose_name='\u5934\u50cf'),
        ),
    ]
