# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 03:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u59d3\u540d')),
                ('dorm_number', models.IntegerField(verbose_name='\u697c\u53f7')),
                ('tel', models.CharField(max_length=255, verbose_name='\u7535\u8bdd')),
                ('fault', models.IntegerField(choices=[(1, b'\xe7\xb3\xbb\xe7\xbb\x9f\xe5\x8d\x87\xe7\xba\xa7\xe3\x80\x81\xe9\x87\x8d\xe8\xa3\x85'), (2, b'\xe7\xb3\xbb\xe7\xbb\x9f\xe6\xbf\x80\xe6\xb4\xbb'), (3, b'\xe8\xbd\xaf\xe4\xbb\xb6\xe5\xae\x89\xe8\xa3\x85'), (4, b'\xe7\x94\xb5\xe8\x84\x91\xe6\xb8\x85\xe7\x81\xb0'), (5, b'\xe6\x97\xa0\xe6\xb3\x95\xe5\xbc\x80\xe6\x9c\xba'), (6, b'\xe6\x97\xa0\xe6\xb3\x95\xe8\x81\x94\xe7\xbd\x91'), (7, b'\xe5\x85\xb6\xe4\xbb\x96')])),
                ('mark', models.TextField(blank=True, default='', verbose_name='\u5907\u6ce8')),
                ('appointment_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u9884\u7ea6\u65f6\u95f4')),
                ('fix_time', models.DateTimeField(default=None, null=True, verbose_name='\u4fee\u7406\u65f6\u95f4')),
                ('fixer', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4fee\u7406\u5458')),
            ],
        ),
    ]
