# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u6545\u969c')),
            ],
        ),
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u59d3\u540d')),
                ('dorm_number', models.IntegerField(verbose_name='\u697c\u53f7')),
                ('tel', models.CharField(max_length=255, verbose_name='\u7535\u8bdd')),
                ('mark', models.TextField(blank=True, default='', verbose_name='\u5907\u6ce8')),
                ('appointment_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u9884\u7ea6\u65f6\u95f4')),
                ('fix_time', models.DateTimeField(default=None, null=True, verbose_name='\u4fee\u7406\u65f6\u95f4')),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fix.Fault', verbose_name='\u6545\u969c')),
            ],
        ),
    ]
