# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u6545\u969c')),
            ],
            options={
                'verbose_name': '\u6545\u969c\u5217\u8868',
                'verbose_name_plural': '\u6545\u969c\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u59d3\u540d')),
                ('dorm_number', models.IntegerField(verbose_name='\u697c\u53f7')),
                ('tel', models.CharField(max_length=255, verbose_name='\u7535\u8bdd')),
                ('mark', models.TextField(blank=True, default='', verbose_name='\u5907\u6ce8')),
                ('appointment_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u9884\u7ea6\u65f6\u95f4')),
                ('fix_time', models.DateTimeField(blank=True, verbose_name='\u4fee\u7406\u65f6\u95f4')),
                ('is_fix', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7ef4\u4fee')),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fix.Fault', verbose_name='\u6545\u969c')),
                ('fixer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4fee\u7406\u5458')),
            ],
            options={
                'ordering': ('is_fix', '-appointment_time'),
                'verbose_name': '\u9884\u7ea6\u540d\u5355',
                'verbose_name_plural': '\u9884\u7ea6\u540d\u5355',
            },
        ),
    ]
