# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fix',
            name='fix_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u4fee\u7406\u65f6\u95f4'),
        ),
    ]
