# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0002_fix_fixer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fault',
            options={'verbose_name': '\u6545\u969c\u5217\u8868', 'verbose_name_plural': '\u6545\u969c\u5217\u8868'},
        ),
        migrations.AlterModelOptions(
            name='fix',
            options={'verbose_name': '\u9884\u7ea6\u540d\u5355', 'verbose_name_plural': '\u9884\u7ea6\u540d\u5355'},
        ),
        migrations.AddField(
            model_name='fix',
            name='is_fix',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u7ef4\u4fee'),
        ),
    ]
