# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0002_auto_20170204_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='fix',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
