# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0004_auto_20170208_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u59d3\u540d')),
                ('sex', models.IntegerField(choices=[(1, b'\xe7\x94\xb7'), (2, b'\xe5\xa5\xb3'), (3, b'\xe4\xbf\x9d\xe5\xaf\x86')], verbose_name='\u6027\u522b')),
                ('tel', models.CharField(max_length=255, verbose_name='\u7535\u8bdd')),
                ('major', models.CharField(max_length=255, verbose_name='\u4e13\u4e1a')),
                ('desc', models.TextField()),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fault',
            options={'ordering': ('order',), 'verbose_name': '\u6545\u969c\u5217\u8868', 'verbose_name_plural': '\u6545\u969c\u5217\u8868'},
        ),
    ]
