# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_opensourceproject_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftWare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('url', models.URLField(blank=True, default='', verbose_name='\u4e0b\u8f7d\u5730\u5740')),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': '\u5e38\u7528\u8f6f\u4ef6',
                'verbose_name_plural': '\u5e38\u7528\u8f6f\u4ef6',
            },
        ),
    ]
