# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20170205_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opensourceproject',
            options={'ordering': ('-order',), 'verbose_name': '\u5f00\u6e90\u9879\u76ee', 'verbose_name_plural': '\u5f00\u6e90\u9879\u76ee'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ('-order',), 'verbose_name': '\u5e38\u7528\u5de5\u5177', 'verbose_name_plural': '\u5e38\u7528\u5de5\u5177'},
        ),
        migrations.AddField(
            model_name='opensourceproject',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6392\u5e8f'),
        ),
        migrations.AddField(
            model_name='tool',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6392\u5e8f'),
        ),
    ]
