# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170208_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opensourceproject',
            options={'ordering': ('order',), 'verbose_name': '\u5f00\u6e90\u9879\u76ee', 'verbose_name_plural': '\u5f00\u6e90\u9879\u76ee'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ('order',), 'verbose_name': '\u5e38\u7528\u5de5\u5177', 'verbose_name_plural': '\u5e38\u7528\u5de5\u5177'},
        ),
    ]
